FROM oraclelinux:7.6@sha256:a6ee3b4c6a52a529a6de77bb25c3d0a99e99e1ad81cd936cd14b100288ffe246
LABEL com.iximiuz-project="docker-to-linux"

RUN mkdir -p /usr/share/info
RUN yum-config-manager --enable ol7_latest
yum -y update
